[package]
name = "cantact-driver"
version = "0.1.0"
authors = ["Eric Evenchick <eric@evenchick.com>"]
edition = "2018"

[lib]
name = "cantact"
crate-type = ["dylib", "rlib"]

[dependencies]
rusb = "0.5"
cpython = { version = "0.5.0", features = ["extension-module"] }
