[package]
name = "cantact-driver"
version = "0.1.0"
authors = ["Eric Evenchick <eric@evenchick.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "cantact"
crate-type = ["dylib", "rlib"]

[[bin]]
name = "candump"
path = "src/bin/candump.rs"

[features]
python = ["cpython"]

[dependencies]
rusb = "0.5"
cpython = { version = "0.5.0", features = ["extension-module"], optional = true }
